/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessCode {
  'subscriberEmail' : string,
  'code' : string,
  'usedAt' : [] | [Time],
  'createdAt' : Time,
  'subscriberName' : string,
  'isUsed' : boolean,
  'reportId' : string,
  'subscriberWhatsapp' : string,
  'transactionId' : string,
}
export interface PaymentSubmission {
  'name' : string,
  'whatsapp' : string,
  'productId' : string,
  'email' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'transactionId' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'createAccessCode' : ActorMethod<
    [string, string, string, string, string, string],
    boolean
  >,
  'deleteAccessCode' : ActorMethod<[string], boolean>,
  'getAccessCodeByCode' : ActorMethod<[string], [] | [AccessCode]>,
  'getAllAccessCodes' : ActorMethod<[], Array<AccessCode>>,
  'getAllPaymentSubmissions' : ActorMethod<[], Array<PaymentSubmission>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemAccessCode' : ActorMethod<
    [string],
    [] | [
      {
        'subscriberEmail' : string,
        'subscriberName' : string,
        'reportId' : string,
      }
    ]
  >,
  'submitPaymentSubmission' : ActorMethod<
    [string, string, string, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];