/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AccessCode = IDL.Record({
  'subscriberEmail' : IDL.Text,
  'code' : IDL.Text,
  'usedAt' : IDL.Opt(Time),
  'createdAt' : Time,
  'subscriberName' : IDL.Text,
  'isUsed' : IDL.Bool,
  'reportId' : IDL.Text,
  'subscriberWhatsapp' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const PaymentSubmission = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'productId' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createAccessCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteAccessCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAccessCodeByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AccessCode)],
      ['query'],
    ),
  'getAllAccessCodes' : IDL.Func([], [IDL.Vec(AccessCode)], ['query']),
  'getAllPaymentSubmissions' : IDL.Func(
      [],
      [IDL.Vec(PaymentSubmission)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemAccessCode' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'subscriberEmail' : IDL.Text,
            'subscriberName' : IDL.Text,
            'reportId' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'submitPaymentSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AccessCode = IDL.Record({
    'subscriberEmail' : IDL.Text,
    'code' : IDL.Text,
    'usedAt' : IDL.Opt(Time),
    'createdAt' : Time,
    'subscriberName' : IDL.Text,
    'isUsed' : IDL.Bool,
    'reportId' : IDL.Text,
    'subscriberWhatsapp' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const PaymentSubmission = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'productId' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createAccessCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteAccessCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAccessCodeByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AccessCode)],
        ['query'],
      ),
    'getAllAccessCodes' : IDL.Func([], [IDL.Vec(AccessCode)], ['query']),
    'getAllPaymentSubmissions' : IDL.Func(
        [],
        [IDL.Vec(PaymentSubmission)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemAccessCode' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'subscriberEmail' : IDL.Text,
              'subscriberName' : IDL.Text,
              'reportId' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'submitPaymentSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };